### ISSUE TITLE
how to collect the metrics of average interconnect usage?

### ISSUE THREAD

**Issue by GH15zzh** [Carrefour/carrefour-runtime#1]
hello,
I am very interested in your article, but some do not understand. You use hardware performance counters to gather the key metrics: memory-controller imbalance, average interconnect usage, average interconnect imbalance and so on.
Can you show us more details？ How to use the perf tool's output to calculate these metrics？
Thank you very much.

**Comment by BLepers** [comment]
We don't use the perf tool output, we use the perf filesystem:

- https://github.com/Carrefour/carrefour-runtime/blob/e48bfdad251f997737b33da7677fc835d698fe29/carrefour.c#L594 opens a perf file descriptor for an event we want to monitor

- https://github.com/Carrefour/carrefour-runtime/blob/e48bfdad251f997737b33da7677fc835d698fe29/carrefour.c#L622 reads the value of a performance counter.
 
- https://github.com/Carrefour/carrefour-runtime/blob/e48bfdad251f997737b33da7677fc835d698fe29/carrefour.c#L641 performs the computations of the imbalance, etc.

**Comment by GH15zzh** [comment]
Can you show me something about the metrics？
For example, if I want to measure "average interconnect usage", what events should I monitor  in perf？such as, bus-cycles ?

**Comment by fgaud** [comment]
You should certainly not look at bus-cycles to evaluate the interconnect usage.

For the memory imbalance, you can take a look at what we are using here:
https://github.com/Carrefour/carrefour-runtime/blob/e48bfdad251f997737b33da7677fc835d698fe29/carrefour.c#L115

You should get your processor's documentation (for example https://support.amd.com/TechDocs/49125_15h_Models_30h-3Fh_BKDG.pdf for amd 15h processors) and construct the event counter that you want (for example 0x1004001E0 for all memory accesses to Memory node 0).

This runtime is not meant to do generic counter profiling, only take decisions based on a subset of counters we are observing (average interconnect usage is not one of them, see our paper for that). If you want generic profiling, you should use the Linux perf tool.
